const SERVER_URL=localStorage.getItem('blokus_server_url')||'http://localhost:8787';
const COLORS={blue:'青',yellow:'黄',red:'赤',green:'緑',orange:'橙',purple:'紫'};
const PIECES=[[[0,0]],[[0,0],[1,0]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[1,0]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[1,0],[1,1]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[0,1],[0,2],[1,2]],[[0,0],[1,0],[1,1],[2,1]],[[0,0],[1,0],[2,0],[3,0],[4,0]],[[0,0],[0,1],[0,2],[0,3],[1,3]],[[0,0],[0,1],[0,2],[1,0],[1,1]],[[0,0],[0,1],[1,1],[1,2],[2,2]],[[0,0],[1,0],[2,0],[3,0],[1,1]],[[0,0],[1,0],[2,0],[0,1],[0,2]],[[0,0],[1,0],[1,1],[2,1],[1,2]],[[0,0],[0,1],[1,1],[2,1],[2,2]],[[0,0],[1,0],[2,0],[1,1],[1,2]],[[0,0],[1,0],[2,0],[2,1],[3,1]],[[0,0],[1,0],[1,1],[1,2],[2,2]],[[0,0],[0,1],[1,1],[1,2],[2,1]]];
let room=null,state=null,token=localStorage.getItem('blokus_token')||crypto.randomUUID(),selected=null,ori=0,flipped=false,hover=null,poll=null;
const $=s=>document.querySelector(s); const nameEl=$('#name'); nameEl.value=localStorage.getItem('boardgame_player_name')||'';
async function api(path,opt={}){let r=await fetch(SERVER_URL+path,{headers:{'content-type':'application/json'},...opt});let j=await r.json();if(!r.ok)throw Error(j.error||'通信エラー');return j}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
async function refreshRooms(){try{let d=await api('/rooms');$('#rooms').innerHTML=d.rooms.map(r=>`<div class="room"><b>ROOM${r.id}</b><small>${r.status}<br>${r.players.join(' / ')||'0人'}</small><button onclick="join(${r.id})">${r.count?'参加':'作成・参加'}</button><button onclick="resetRoom(${r.id})">初期化</button></div>`).join('')}catch(e){$('#msg').textContent='サーバー未接続: '+e.message}}
window.resetRoom=async id=>{if(!confirm('ROOM'+id+'を初期化しますか？'))return;try{await api('/room/'+id+'/reset',{method:'POST',body:JSON.stringify({name:nameEl.value})});refreshRooms()}catch(e){alert(e.message)}};
window.join=async id=>{let name=nameEl.value.trim();if(!name)return alert('名前を入力してください');try{let d=await api('/room/'+id+'/join',{method:'POST',body:JSON.stringify({name,token})});room=id;localStorage.setItem('blokus_token',token);state=d.state;showGame();startPoll()}catch(e){alert(e.message)}};
function showGame(){$('#lobby').hidden=true;$('#game').hidden=false;render()}
function startPoll(){clearInterval(poll);poll=setInterval(sync,900)} async function sync(){if(!room)return;try{let d=await api('/room/'+room+'/state?token='+encodeURIComponent(token));state=d.state;render()}catch(e){}}
function myPlayer(){return state?.players.find(p=>p.token===token)}
function render(){if(!state)return;let n=state.size;$('#board').style.gridTemplateColumns=`repeat(${n},1fr)`;let starts=new Set((state.starts||[]).map(p=>p.join(',')));$('#board').innerHTML=state.board.flatMap((row,y)=>row.map((c,x)=>`<div class="cell ${c||''} ${starts.has(x+','+y)?'start':''}" data-x="${x}" data-y="${y}"></div>`)).join('');
$('#board').querySelectorAll('.cell').forEach(c=>{c.onmouseenter=()=>preview(+c.dataset.x,+c.dataset.y);c.onclick=()=>place(+c.dataset.x,+c.dataset.y);c.ontouchstart=e=>{e.preventDefault();preview(+c.dataset.x,+c.dataset.y)}});let cur=state.turns[state.turnIndex];$('#turnText').textContent=state.phase==='lobby'?'ロビー待機':state.phase==='finished'?'ゲーム終了':`${cur?.name||''} / ${COLORS[cur?.color]||''} の手番`;
$('#players').innerHTML=state.players.map(p=>`<div class="player ${cur?.token===p.token?'active':''}"><b>${p.name}${p.cpu?' [CPU]':''}</b><br>${p.colors.map(c=>COLORS[c]).join('・')}<br>残り ${p.remainingSquares}マス</div>`).join('');
if(state.phase==='lobby'){renderLobbyModal();return} if(state.phase==='finished'){renderResult();return} $('#modal').hidden=true;renderPieces()}
function renderLobbyModal(){let me=myPlayer(),host=state.players[0]?.token===token;$('#modal').hidden=false;let count=state.players.length;$('#modalBody').innerHTML=`<h2>ROOM${room} ロビー</h2><p>${state.players.map(p=>p.name+(p.cpu?' [CPU]':'')).join('<br>')}</p>${host?`<button onclick="addCpu()">CPU追加</button>${count===2?`<p>2人ルール</p><select id="mode"><option value="classic2">クラシック（1人2色 / 20×20）</option><option value="duo">Blokus Duo（1人1色 / 14×14）</option></select>`:''}<p>CPU Lv <select id="cpuLv"><option>1</option><option selected>2</option><option>3</option></select></p><button onclick="startGame()">ゲーム開始</button>`:'<p>ホストの開始を待っています</p>'}<button onclick="leaveRoom()">退出</button>`}
window.addCpu=async()=>{try{await act('addCpu',{level:+($('#cpuLv')?.value||2)})}catch(e){alert(e.message)}};window.startGame=async()=>{try{await act('start',{mode:$('#mode')?.value||null,cpuLevel:+($('#cpuLv')?.value||2)})}catch(e){alert(e.message)}};
async function act(type,data={}){let d=await api('/room/'+room+'/action',{method:'POST',body:JSON.stringify({token,type,...data})});state=d.state;render()}
function transforms(shape){let pts=shape.map(([x,y])=>[flipped?-x:x,y]);for(let i=0;i<ori;i++)pts=pts.map(([x,y])=>[-y,x]);let minx=Math.min(...pts.map(p=>p[0])),miny=Math.min(...pts.map(p=>p[1]));return pts.map(([x,y])=>[x-minx,y-miny])}
function renderPieces(){let me=myPlayer(),cur=state.turns[state.turnIndex];let color=cur?.token===token?cur.color:null;if(!color){$('#pieces').innerHTML='';return}let used=new Set(state.used[color]||[]);let rem=PIECES.map((p,i)=>!used.has(i)?p.length:0).reduce((a,b)=>a+b,0);$('#remain').textContent=rem+'マス';$('#pieces').innerHTML=PIECES.map((p,i)=>used.has(i)?'':`<button class="piece ${selected===i?'sel':''}" onclick="selPiece(${i})"><span>${i+1}</span><small>${p.length}マス</small></button>`).join('')}
window.selPiece=i=>{selected=i;ori=0;flipped=false;renderPieces()};$('#rot').onclick=()=>{ori=(ori+1)%4;if(hover)preview(...hover)};$('#flip').onclick=()=>{flipped=!flipped;if(hover)preview(...hover)};$('#cancel').onclick=()=>{selected=null;hover=null;render()};
function preview(x,y){hover=[x,y];render();if(selected==null)return;let pts=transforms(PIECES[selected]);let ok=true;for(let [dx,dy] of pts){let c=$(`.cell[data-x="${x+dx}"][data-y="${y+dy}"]`);if(!c){ok=false;continue}c.classList.add('preview')}if(!ok)for(let [dx,dy] of pts){let c=$(`.cell[data-x="${x+dx}"][data-y="${y+dy}"]`);c?.classList.add('bad')}}
async function place(x,y){if(selected==null)return;try{await act('place',{piece:selected,cells:transforms(PIECES[selected]).map(([dx,dy])=>[x+dx,y+dy])});selected=null;hover=null}catch(e){toast(e.message)}}
function renderResult(){if(!$('#modal').hidden)return;$('#modal').hidden=false;let rows=state.results.map((r,i)=>`<p>${i+1}位 ${r.name}：${r.score}点</p>`).join('');$('#modalBody').innerHTML=`<h2>ゲーム終了</h2>${rows}<button onclick="closeResult()">盤面を見る</button><button onclick="backLobby()">ロビーへ戻る</button>`}window.closeResult=()=>$('#modal').hidden=true;window.backLobby=async()=>act('backLobby');
window.leaveRoom=async()=>{try{await act('leave')}catch{}room=null;state=null;clearInterval(poll);$('#game').hidden=true;$('#lobby').hidden=false;refreshRooms()};$('#leave').onclick=leaveRoom;$('#pin').onclick=()=>toast('盤面をピン留めしました');
refreshRooms();setInterval(()=>{if(!room)refreshRooms()},3000);